server:
  port: 8080
  servlet:
    context-path: /hresource
spring:
  application:
    name: hresource
  datasource:
    url: jdbc:postgresql://172.18.0.5:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  #  data:
  #    rest:
  #      base-path: /hresource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
